# -*- coding: utf-8 -*-
"""
Created on 2024-05-29 21:14:00
---------
@summary:
---------
@author: hejie
"""

from feapder import Item


class WpShopInfoItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i wp_shop_info
    """

    __table_name__ = "wp_shop_info"

    def __init__(self, *args, **kwargs):
        super().__init__(**kwargs)
        # self.id = None
        self.title = None
        self.price = None
