# -*- coding: utf-8 -*-
"""
Created on 2024-05-27 15:51:09
---------
@summary:
---------
@author: hejie
"""

from feapder import Item


class DoubanFeapderItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i douban_feapder
    """

    __table_name__ = "douban_feapder"

    def __init__(self, *args, **kwargs):
        super().__init__(**kwargs) # 框架默认没有调用父类的构造方法
        # self.id = None # id无需进行字段验证
        self.title = None
        self.score = None
        self.detail_url = None
        self.detail_text = None
